export const PUBLICATION_IMPORT_UPLOAD_MAX_MEGABYTES = 50;
export const PUBLICATION_IMPORT_UPLOAD_MAX_BYTES =
  PUBLICATION_IMPORT_UPLOAD_MAX_MEGABYTES * 1024 * 1024;
export const PUBLICATION_IMPORT_UPLOAD_MAX_LABEL = `${String(
  PUBLICATION_IMPORT_UPLOAD_MAX_MEGABYTES,
)} MB`;
